-- Den Samot Warehouse Employees (69 total)
-- Run in Supabase SQL Editor
-- Uses (SELECT id FROM ds_locations LIMIT 1) to auto-pick the warehouse location

INSERT INTO ds_employees (id, name, department, location_id, is_active)
VALUES
  ('1', 'ទិន ភាព', 'ប្រធាន', (SELECT id FROM ds_locations LIMIT 1), true),
  ('2', 'មាស មុន្នីកា', 'រដ្ឋបាល', (SELECT id FROM ds_locations LIMIT 1), true),
  ('3', 'គា សាវ៉ៃ', 'ចេញបុង', (SELECT id FROM ds_locations LIMIT 1), true),
  ('4', 'នួន ដានី', 'គណនេយ្យ', (SELECT id FROM ds_locations LIMIT 1), true),
  ('5', 'សំ ឆៃដែន', 'ស្តុកទូកក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('6', 'ឈួន បូរិន', 'អាងត្រី', (SELECT id FROM ds_locations LIMIT 1), true),
  ('7', 'សេង សុកុល', 'ស្តុកមឹឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('8', 'ឈួន បូរៃ', 'ជាងជួសជុល', (SELECT id FROM ds_locations LIMIT 1), true),
  ('9', 'ឈួន ឆេង (តា)', 'បេះមឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('10', 'យាយ', 'ចុងភៅ', (SELECT id FROM ds_locations LIMIT 1), true),
  ('11', 'សំណាង', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('12', 'យ៉ែន ពៅ', 'បេះមឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('13', 'ស៊ិន ពេជ្រសុវត្ត', 'អាងយប់', (SELECT id FROM ds_locations LIMIT 1), true),
  ('14', 'ម៉េង ហាក់់', 'មេក្រុមឡាន', (SELECT id FROM ds_locations LIMIT 1), true),
  ('15', 'តៃ រ៉ាត់', 'ឡាន', (SELECT id FROM ds_locations LIMIT 1), true),
  ('16', 'នុង សោភាស់', 'ឡាន', (SELECT id FROM ds_locations LIMIT 1), true),
  ('17', 'រ៉ាន់ សុភ័ក្រ', 'ឡាន', (SELECT id FROM ds_locations LIMIT 1), true),
  ('18', 'ម៉េង អាង', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('19', 'ម៉ៃ ឆាន់នី', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('20', 'យ៉ាត វាសនា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('21', 'ស្រេង រ៉ាឌី', 'ឡាន', (SELECT id FROM ds_locations LIMIT 1), true),
  ('22', 'ឈុន អេង', 'អាងបង្គា', (SELECT id FROM ds_locations LIMIT 1), true),
  ('23', 'កែន រុង', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('24', 'នឹម ស្រីម៉ៃ', 'ការិយល័យ', (SELECT id FROM ds_locations LIMIT 1), true),
  ('25', 'រ័ត្ន ផាណាក់', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('26', 'ជូ វុទ្ធី', 'ស្តុកកន្ធាយ', (SELECT id FROM ds_locations LIMIT 1), true),
  ('27', 'ងន ម៉ាប់', 'ទីផ្សារ', (SELECT id FROM ds_locations LIMIT 1), true),
  ('28', 'គីម ឡា', 'ឡាន', (SELECT id FROM ds_locations LIMIT 1), true),
  ('29', 'សម្បត្តិ', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('30', 'ស៊ុន កំសត់', 'អាងបង្គា', (SELECT id FROM ds_locations LIMIT 1), true),
  ('31', 'វីដ', 'អាងយប់', (SELECT id FROM ds_locations LIMIT 1), true),
  ('32', 'មឿន រ៉ាឌី', 'បេះមឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('33', 'ងួន សុខមាន', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('34', 'យ៉ន សុវណ្ណរាជ', 'ចែកអីវ៉ាន់', (SELECT id FROM ds_locations LIMIT 1), true),
  ('35', 'ជ្រា ប៉េងណា', 'IT Teacher', (SELECT id FROM ds_locations LIMIT 1), true),
  ('36', 'យឿន ម៉ាន់យ៉ា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('37', 'ស៊ិន ទីណូ', 'បេះមឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('38', 'រ៉ាំ រ៉ាឌីន', 'បេះមឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('39', 'ឆាំ រឹឆាត', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('40', 'ជូ វុត្ថា', 'បេះមឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('41', 'សាន់ ប្រុស', 'បេះមឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('42', 'ម៉េង ហ័ង', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('43', 'ជា ភារ័ត្ន', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('44', 'សាន្ត ស៊ីដេត', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('45', 'សុភក្រ្ត ភីនិត', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('46', 'ជូ សីហា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('47', 'ជា តារា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('48', 'វ៉ាង សុផៃ', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('49', 'វ៉ាន់ វ៉ាត', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('50', 'ក្រាត សាង', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('51', 'សៀប យីម', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('52', 'ថា ម៉េងអាន', 'អាងយប់', (SELECT id FROM ds_locations LIMIT 1), true),
  ('53', 'ទូច ចំរើន', 'អាងយប់', (SELECT id FROM ds_locations LIMIT 1), true),
  ('54', 'នី លៀងស៊ីម', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('55', 'ពៅ សុផៃ', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('56', 'វឿន បញ្ញា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('57', 'គី សុខគា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('58', 'លិញ តុលា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('59', 'តាន់ វីរូត', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('60', 'ម៉ោង ថា', 'វេនយប់', (SELECT id FROM ds_locations LIMIT 1), true),
  ('61', 'នី សុខណាត', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('62', 'អ៊ី សំណាង (បញ្ញា)', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('63', 'ឈួន តោ', 'វេនយប់', (SELECT id FROM ds_locations LIMIT 1), true),
  ('64', 'សូយ ណបភី', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('65', 'ផល សុភាស់', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('66', 'យឿន លីណា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('67', 'យ៉ែម សុខលីន', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('68', 'ខន ឆៃឌី', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true),
  ('69', 'វណ្ណៈ ធារ៉ា', 'ដឹក', (SELECT id FROM ds_locations LIMIT 1), true);
